api_delete:
    path:     /delete/{identifier}
    defaults: { _controller: itsgoingtobe.api_controller:deleteAction }
    methods: ['POST']

api_question:
    path:     /question
    defaults: { _controller: itsgoingtobe.api_controller:questionAction }
    methods: ['POST']

api_answer:
    path:     /{identifier}/answer
    defaults: { _controller: itsgoingtobe.api_controller:answerAction }
    methods: ['POST']

api_responses:
    path:     /{identifier}/responses
    defaults: { _controller: itsgoingtobe.api_controller:responsesAction }
    methods: ['GET']