api_poll:
    path:     /polls/{identifier}
    defaults: { _controller: itsgoingtobe.api_controller:pollsAction, identifier: 0 }

api_poll_responses:
    path:     /polls/{identifier}/responses
    defaults: { _controller: itsgoingtobe.api_controller:responsesAction, identifier: 0 }
