api_poll:
    path:     /polls/{identifier}
    defaults: { _controller: itsgoingtobe.poll_api_controller:apiAction, identifier: 0 }

api_poll_responses:
    path:     /polls/{identifier}/responses
    defaults: { _controller: itsgoingtobe.response_api_controller:apiAction, identifier: 0 }

api_login:
    path:     /login
    defaults: { _controller: itsgoingtobe.login_api_controller:apiAction, identifier: 0 }
