index_page:
    path:     /
    defaults: { _controller: ItsGoingToBeBundle:ItsGoingToBe:index }

answer_page:
    path:     /{identifier}
    defaults: { _controller: itsgoingtobe.itsgoingtobe_controller:answerAction }