index_page:
    path:     /
    defaults: { _controller: ItsGoingToBeBundle:ItsGoingToBe:index }

answer_page:
    path:     /{identifier}
    defaults: { _controller: itsgoingtobe.itsgoingtobe_controller:answerAction }

delete:
    path:     /delete/{identifier}
    defaults: { _controller: itsgoingtobe.itsgoingtobe_controller:deleteAction }
    methods: ['POST']

question:
    path:     /question
    defaults: { _controller: itsgoingtobe.itsgoingtobe_controller:questionAction }
    methods: ['POST']

answer:
    path:     /{identifier}/answer
    defaults: { _controller: itsgoingtobe.itsgoingtobe_controller:answerPostAction }
    methods: ['POST']

responses:
    path:     /{identifier}/responses
    defaults: { _controller: itsgoingtobe.itsgoingtobe_controller:responsesAction }
    methods: ['GET']