language: php

php:
  - 5.6

cache:
  directories:
    - vendor
    - node_modules

branches:
  only:
    - master
    - develop

before_install:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - cp app/config/parameters.yml.travis app/config/parameters_dev.yml
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

install:
  - phpenv config-rm xdebug.ini
  - composer install
  - npm install

before_script:
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

script:
  - bin/phpcs --standard=PSR2 src/
  - bin/phplint src
  - bin/phpunit -c app
  - npm run lint
  - npm run test

notifications:
  email:
    -  sprog31@gmail.com
