sudo: required
dist: trusty

language: php

php:
  - '7.2'

services:
  - mysql

env:
  global:
    - APP_ENV=test
    - USER="Travis CI"
    - EMAIL="travis@travis-ci.org"
    - GITHUB_REPO="github.com/${TRAVIS_REPO_SLUG}.git"
  matrix:
    - NODE_VERSION=8

addons:
  sonarcloud:
    organization: "sproogen-github"

cache:
  directories:
    - $HOME/.composer/cache/file
    - vendor
    - app/node_modules

branches:
  only:
    - master
    - develop

before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $NODE_VERSION && nvm install-latest-npm
  - ./scripts/bump-version.sh

install:
  - composer install
  - (cd app && npm ci)

before_script:
  - php bin/console about
  - php bin/console doctrine:database:create
  - composer compile

script:
  - vendor/bin/phpcs --standard=PSR2 --ignore=Migrations src/
  - vendor/bin/phplint src
  - SYMFONY_DEPRECATIONS_HELPER=disabled vendor/bin/simple-phpunit
  - SYMFONY_DEPRECATIONS_HELPER=disabled vendor/bin/codecept run --coverage-xml
  - (cd app && npm run lint)
  - (cd app && npm run test -- --coverage --ci)
  - ./scripts/update-sonar-version.sh && sonar-scanner

after_success:
  - ./scripts/merge-downstream.sh

notifications:
  slack:
    rooms:
      secure: IOSY99/p0I2R6MeUVpAEjyC7MRacRbXDcr9G8ImzWG6HP9hHxFk3Wyyhnz03AfKenu2PtAYW3rHKj6dciPsXBrJjcX5FT8np3ZWlGG4OxVjV8nMdHtU83z2uk+gfJ+4du9pIQrbu17JIJlP+uJKyc+qoOqFaIg6vRVdQ00LF7WWwTHyYI+ncRsypUnjDEqx9EpUaAHXthmVHseJX43YF9GcBLOZ1WktmHaqsjUV0o7O2ssOkloGDwfDeUAHd6M9smfyHkdpAHYxD5HRXaoPxyLPMrz2X4BH1rApXdbJ+KWIdY8UJzwdh5TJeoDqheP+CJx6SG1bAAOU8awEdtw1tNE3ohPSZPM/gpj88P6LrSvyoqB4QxjuX0jcpArGyKxJy4pJNW13t3Vtua9VUpfsQsyfIkzpFEPPr8ADz4Z9MD3MOHDt9/TlFJWALRb+JgMjbqyb0wsm5yxm81v8yS+9420iviVzMCNI7Qx+r+Lb01C8x0lkrHW4cp3+4PNYoilTe0qyp6qpa/aryIbxR5PVvIDttu1Wn0Y5ddD1hsaiLstgoUSmWkaNSyq//zpE0y820CLfePWeZqaEtMxt8EEmCALOw/s8Iz5pja4Vlzm1gaDAI7TR1jFCuRE08eQ+lz5QvQNYuBdaDyp6v8X/jMeQqcjYeCxDvk2UrZUzh2OMO9uI=

