sudo: required
dist: trusty

language: php

php:
  - '7.2'

services:
  - mysql

env:
  - NODE_VERSION=8.x APP_ENV=test

cache:
  directories:
    - $HOME/.composer/cache/file
    - vendor
    - app/node_modules

branches:
  only:
    - master
    - develop

before_install:
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs

install:
  - composer install
  - (cd app && npm ci)

before_script:
  - php bin/console doctrine:database:create
  - composer compile

script:
  - vendor/bin/phpcs --standard=PSR2 --ignore=Migrations src/
  - vendor/bin/phplint src
  - vendor/bin/phpunit
  - SYMFONY_DEPRECATIONS_HELPER=disabled vendor/bin/codecept run
  - (cd app && npm run build)
  - (cd app && npm run lint)
  - (cd app && npm run test -- --coverage --ci)

after_script:
  - vendor/bin/codacycoverage clover build/logs/clover.xml
  - (cd app && cat build/coverage/lcov.info | node_modules/.bin/codacy-coverage .)

notifications:
  email:
    -  sprog31@gmail.com
