language: php

php:
  - 5.6

env:
  - NODE_VERSION="7"

cache:
  directories:
    - vendor
    - node_modules

branches:
  only:
    - master
    - develop

before_install:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - cp app/config/parameters.yml.travis app/config/parameters_dev.yml
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install NODE_VERSION

install:
  - phpenv config-rm xdebug.ini
  - composer install
  - npm install

before_script:
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

script:
  - bin/phpcs --standard=PSR2 src/
  - bin/phplint src
  - bin/phpunit -c app
  - npm run lint
  - npm run test

notifications:
  email:
    -  sprog31@gmail.com
