sudo: required
dist: trusty

language: php

php:
  - '7.2'

services:
  - mysql

env:
  - NODE_VERSION=8.x APP_ENV=test

cache:
  directories:
    - $HOME/.composer/cache/file
    - vendor
    - app/node_modules

branches:
  only:
    - master
    - develop

before_install:
  - - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $NODE_VERSION && nvm install-latest-npm

install:
  - composer install
  - (cd app && npm ci)

before_script:
  - php bin/console doctrine:database:create
  - composer compile

script:
  - vendor/bin/phpcs --standard=PSR2 --ignore=Migrations src/
  - vendor/bin/phplint src
  - vendor/bin/phpunit
  - SYMFONY_DEPRECATIONS_HELPER=disabled vendor/bin/codecept run
  - (cd app && npm run build)
  - (cd app && npm run lint)
  - (cd app && npm run test -- --coverage --ci)

after_script:
  - vendor/bin/codacycoverage clover build/logs/clover.xml
  - (cd app && cat build/coverage/lcov.info | node_modules/.bin/codacy-coverage .)

notifications:
  email:
    -  sprog31@gmail.com
