language: php

php:
    - 5.6

cache:
  directories:
    - vendor
    - node_modules
    - app/Resources/client/node_modules

branches:
  only:
    - master
    - develop

before_install:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - cp app/config/parameters.yml.travis app/config/parameters_dev.yml

install:
  - phpenv config-rm xdebug.ini
  - composer install
  - npm install
  - npm install --prefix app/Resources/client/

before_script:
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

script:
  - bin/phpcs --standard=PSR2 src/
  - bin/phplint src
  - bin/phpunit -c app
  - npm run lint --prefix app/Resources/client/

notifications:
  email:
    -  sprog31@gmail.com
