language: php

php:
  - 5.6

services:
  - mysql

env:
  - NODE_VERSION="7"

cache:
  directories:
    - $HOME/.composer/cache/file
    - vendor
    - app/Resources/client/node_modules

branches:
  only:
    - master
    - develop

before_install:
  - cp app/config/parameters.yml.travis app/config/parameters.yml

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $NODE_VERSION
  - composer install
  - (cd app/Resources/client && npm install)

before_script:
  - php bin/console doctrine:database:create --env=test
  - composer compile-test

script:
  - bin/phpcs --standard=PSR2 src/
  - bin/phplint src
  - bin/phpunit
  - SYMFONY_DEPRECATIONS_HELPER=disabled bin/codecept run --ext DotReporter
  - (cd app/Resources/client && npm run lint)
  - (cd app/Resources/client && npm run test)

after_script:
  - bin/codacycoverage clover build/logs/clover.xml
  - cat build/coverage/lcov.info | node_modules/.bin/codacy-coverage .

notifications:
  email:
    -  sprog31@gmail.com
