version: '2'
services:
  app:
    build:
      context: ./app/Resources/client
      dockerfile: docker/app/Dockerfile
    image: itsgoingtobe/app
    volumes:
      - ./app/Resources/client/src:/app/src
    ports:
      - "3000:3000"

  storybook:
    build:
      context: ./app/Resources/client
      dockerfile: docker/storybook/Dockerfile
    image: itsgoingtobe/storybook
    volumes:
      - ./app/Resources/client/src:/app/src
      - ./app/Resources/client/stories:/app/stories
    ports:
      - "6006:6006"

  webserver:
    image: nginx:alpine
    depends_on:
      - php-fpm
    links:
      - mysql
      - mysql:database
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

  php-fpm:
    build: docker/php-fpm
    image: itsgoingtobe/php-fpm
    working_dir: /var/www/html
    depends_on:
      - mysql
    links:
      - mysql
      - mysql:database
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=itsgoingtobe
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password