api_poll:
    path:     /polls/{identifier}
    defaults: { _controller: App\Controller\Api\PollApiController::apiAction, identifier: 0 }

api_poll_responses:
    path:     /polls/{identifier}/responses
    defaults: { _controller: App\Controller\Api\ResponseApiController::apiAction, identifier: 0 }

api_login:
    path:     /login
    defaults: { _controller: App\Controller\Api\LoginApiController::apiAction, identifier: 0 }
