itsgoingtobe_api:
    resource: "api.yml"
    prefix: /api

itsgoingtobe_react:
    path: /{url}
    defaults: { _controller: itsgoingtobe.react_controller:indexAction, url: null }
    requirements:
        url: .*
