security:
    providers:
        database_users:
            entity: { class: ItsGoingToBeBundle:User, property: username }

    encoders:
        ItsGoingToBeBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            guard:
              authenticators:
                  - 'itsgoingtobe.security.token_authenticator'
