itsgoingtobe_pages:
    pattern: /react/{url}
    defaults: { _controller: ItsGoingToBeBundle:React:index, url: null }
    requirements:
        url: .*

itsgoingtobe_admin:
    resource: "@ItsGoingToBeBundle/Resources/config/routing/admin.yml"
    prefix: /admin

itsgoingtobe_api:
    resource: "@ItsGoingToBeBundle/Resources/config/routing/api.yml"
    prefix: /api

itsgoingtobe_pages:
    resource: "@ItsGoingToBeBundle/Resources/config/routing/pages.yml"
    prefix: /
