itsgoingtobe_admin:
    resource: "@ItsGoingToBeBundle/Resources/config/routing/admin.yml"
    prefix: /admin

itsgoingtobe_pages:
    resource: "@ItsGoingToBeBundle/Resources/config/routing/pages.yml"
    prefix: /