services:
    itsgoingtobe.identifier_service:
        class: ItsGoingToBeBundle\Service\IdentifierService
        calls:
            - [ setLogger, ["@logger"]]

    itsgoingtobe.api_controller:
        class: ItsGoingToBeBundle\Controller\ApiController
        calls:
            - [ setContainer, ["@service_container"]]
            - [ setEntityManager, ["@doctrine.orm.default_entity_manager"]]
            - [ setAuthorizationChecker, ["@security.authorization_checker"]]
            - [ setIdentifierService, ["@itsgoingtobe.identifier_service"]]

    itsgoingtobe.itsgoingtobe_controller:
        class: ItsGoingToBeBundle\Controller\ItsGoingToBeController
        calls:
            - [ setContainer, ["@service_container"] ]
            - [ setIdentifierService, ["@itsgoingtobe.identifier_service"]]

    app.twig_extension:
        class: ItsGoingToBeBundle\Twig\AutoLinkTwigExtension
        public: false
        tags:
            - { name: twig.extension }
