services:
    itsgoingtobe.security.authentication_failure_event_listener:
        class: ItsGoingToBeBundle\Service\AuthenticationListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request_stack"
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }

    itsgoingtobe.security.interactive_login_listener:
        class: ItsGoingToBeBundle\Service\AuthenticationListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request_stack"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }

    itsgoingtobe.authorization_checker:
        class: ItsGoingToBeBundle\Security\AuthorizationChecker
        arguments:
            - "@security.authorization_checker"
            - "@request_stack"

    itsgoingtobe.identifier_service:
        class: ItsGoingToBeBundle\Service\IdentifierService
        calls:
            - [ setLogger, ["@logger"]]

    itsgoingtobe.poll_api_controller:
        class: ItsGoingToBeBundle\Controller\Api\PollApiController
        calls:
            - [ setContainer, ["@service_container"]]
            - [ setEntityManager, ["@doctrine.orm.default_entity_manager"]]
            - [ setAuthorizationChecker, ["@itsgoingtobe.authorization_checker"]]
            - [ setIdentifierService, ["@itsgoingtobe.identifier_service"]]

    itsgoingtobe.response_api_controller:
        class: ItsGoingToBeBundle\Controller\Api\ResponseApiController
        calls:
            - [ setContainer, ["@service_container"]]
            - [ setEntityManager, ["@doctrine.orm.default_entity_manager"]]
            - [ setAuthorizationChecker, ["itsgoingtobe.authorization_checker"]]
            - [ setIdentifierService, ["@itsgoingtobe.identifier_service"]]

    itsgoingtobe.react_controller:
        class: ItsGoingToBeBundle\Controller\ReactController
        calls:
            - [ setContainer, ["@service_container"]]
            - [ setEntityManager, ["@doctrine.orm.default_entity_manager"]]
