services:
    itsgoingtobe.security.authentication_failure_event_listener:
        class: ItsGoingToBeBundle\Service\AuthenticationListener
        arguments:
            - @doctrine.orm.entity_manager
            - @request_stack
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }

    itsgoingtobe.security.interactive_login_listener:
        class: ItsGoingToBeBundle\Service\AuthenticationListener
        arguments:
            - @doctrine.orm.entity_manager
            - @request_stack
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }

    itsgoingtobe.identifier_service:
        class: ItsGoingToBeBundle\Service\IdentifierService
        calls:
            - [ setLogger, ["@logger"]]

    itsgoingtobe.api_controller:
        class: ItsGoingToBeBundle\Controller\ApiController
        calls:
            - [ setContainer, ["@service_container"]]
            - [ setEntityManager, ["@doctrine.orm.default_entity_manager"]]
            - [ setAuthorizationChecker, ["@security.authorization_checker"]]
            - [ setIdentifierService, ["@itsgoingtobe.identifier_service"]]

    itsgoingtobe.itsgoingtobe_controller:
        class: ItsGoingToBeBundle\Controller\ItsGoingToBeController
        calls:
            - [ setContainer, ["@service_container"] ]
            - [ setIdentifierService, ["@itsgoingtobe.identifier_service"]]
