services:
    itsgoingtobe.security.token_authenticator:
        class: ItsGoingToBeBundle\Security\TokenAuthenticator
        arguments: ['@lexik_jwt_authentication.encoder.default', '@doctrine.orm.entity_manager']

    itsgoingtobe.identifier_service:
        class: ItsGoingToBeBundle\Service\IdentifierService
        calls:
            - [ setLogger, ["@logger"]]

    itsgoingtobe.poll_end_service:
        class: ItsGoingToBeBundle\Service\PollEndService
        calls:
            - [ setEntityManager, ["@doctrine.orm.default_entity_manager"]]

    itsgoingtobe.poll_api_controller:
        class: ItsGoingToBeBundle\Controller\Api\PollApiController
        calls:
            - [ setContainer, ["@service_container"]]
            - [ setEntityManager, ["@doctrine.orm.default_entity_manager"]]
            - [ setAuthorizationChecker, ["@security.authorization_checker"]]
            - [ setIdentifierService, ["@itsgoingtobe.identifier_service"]]
            - [ setPollEndService, ["@itsgoingtobe.poll_end_service"]]

    itsgoingtobe.response_api_controller:
        class: ItsGoingToBeBundle\Controller\Api\ResponseApiController
        calls:
            - [ setContainer, ["@service_container"]]
            - [ setEntityManager, ["@doctrine.orm.default_entity_manager"]]
            - [ setAuthorizationChecker, ["@security.authorization_checker"]]
            - [ setIdentifierService, ["@itsgoingtobe.identifier_service"]]
            - [ setPollEndService, ["@itsgoingtobe.poll_end_service"]]

    itsgoingtobe.login_api_controller:
        class: ItsGoingToBeBundle\Controller\Api\LoginApiController
        calls:
            - [ setContainer, ["@service_container"]]
            - [ setEntityManager, ["@doctrine.orm.default_entity_manager"]]

    itsgoingtobe.react_controller:
        class: ItsGoingToBeBundle\Controller\ReactController
        calls:
            - [ setContainer, ["@service_container"]]
            - [ setEntityManager, ["@doctrine.orm.default_entity_manager"]]
