ItsGoingToBeBundle\Entity\LoginAttempt:
    type: entity
    table: login_attempt
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        ip:
            type: text
            column: ip
        succesful:
            type: boolean
            column: succesful
        username:
            type: text
            column: username
        password:
            type: text
            column: password
        created:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ prePersist ]
